#
# This file is part of Saft.
#
# (c) Konrad Abicht <hi@inspirito.de>
# (c) Natanael Arndt <arndt@informatik.uni-leipzig.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

language: php

php:
    - '7.1'
    - '7.2'
    - nightly

matrix:
    fast_finish: true

git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - travis_retry composer install --dev --no-interaction
    # Install coveralls.phar
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.1.0/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version

script: vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_success:
  # Submit coverage report to Coveralls servers, see .coveralls.yml
  - travis_retry php coveralls.phar -v
